language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - pip install . --quiet
  - pip install pytest pytest-cov pytest-pep8

script: py.test --cov flask_jwt --cov-report term-missing --pep8

branches:
  only:
    - master
