language: python

python:
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - pip install . --quiet
  - pip install pytest pytest-cov pytest-pep8 coveralls

script: coverage run --source=flask_jwt setup.py test

after_script:
  - coveralls

branches:
  only:
    - master
